### ISSUE TITLE
Add support SUPPORT TICKET SYSTEM - XENFORO 2 ADD-ON

### ISSUE THREAD

**Issue by bolandnick18** [VersoBit/XF-ResourceTickets#23]
Can you please add support for SUPPORT TICKET SYSTEM - XENFORO 2 ADD-ON.

more information:
[https://brivium.com/resources/support-ticket-system-xenforo-2-add-on.394/]

**Comment by tom-coward** [comment]
The main barrier to this would be a) not having a licence for this and b) the main reason we could do this so easily with NixFifty's tickets is his uses of services to create tickets, which we could easily call ourselves - we obviously don't know if this is the case with Brivium's addon.

We're also not sure we'd work on anything Brivium given their somewhat tainted standing in the XF community.

**Comment by RyleaStark** [comment]
I will be closing this issue because Brivium's Addon has been unsupported for many years and we only intend on working with NixFifty for this extension. You can purchase a copy of NixFifty's add-on here: **https://nixfifty.com/products/tickets.2**

**Comment by TylerAustin7** [comment]
I don't thing i will be using nixfifty tickets addon at all
